
stages:
  - build

docker_build:

  stage: build

  image: docker:latest

  tags:
    - docker

  script:

    # log in to our container registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

    # build the image
    - docker build -t $CI_REGISTRY_IMAGE:latest .

    # push the image to our registry
    - docker push $CI_REGISTRY_IMAGE:latest